package chapter3

import org.scalatest.Matchers._
import org.scalatest.{BeforeAndAfterEach, FlatSpec}

import scala.util.Random

class Exercise6Test extends FlatSpec with BeforeAndAfterEach {

  private val random = Random
  private val test = (for (_ <- 1 to 10) yield random.nextInt(200) - 100).toArray
  private val result = test.clone()
  Exercise6.reverseSort(result)

  s"The reverse sort of ${test.mkString("Array(", ", ", ")")}" should "be equal to the one generated by the API" in {
    result should contain theSameElementsInOrderAs test.sorted(Ordering[Int].reverse)
  }
}
